// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: swapdoodle.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Swapdoodle_GetPresignedUrlForReportId_FullMethodName = "/swapdoodle.Swapdoodle/GetPresignedUrlForReportId"
)

// SwapdoodleClient is the client API for Swapdoodle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwapdoodleClient interface {
	GetPresignedUrlForReportId(ctx context.Context, in *GetPresignedUrlForReportIdRequest, opts ...grpc.CallOption) (*GetPresignedUrlForReportIdResponse, error)
}

type swapdoodleClient struct {
	cc grpc.ClientConnInterface
}

func NewSwapdoodleClient(cc grpc.ClientConnInterface) SwapdoodleClient {
	return &swapdoodleClient{cc}
}

func (c *swapdoodleClient) GetPresignedUrlForReportId(ctx context.Context, in *GetPresignedUrlForReportIdRequest, opts ...grpc.CallOption) (*GetPresignedUrlForReportIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedUrlForReportIdResponse)
	err := c.cc.Invoke(ctx, Swapdoodle_GetPresignedUrlForReportId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwapdoodleServer is the server API for Swapdoodle service.
// All implementations must embed UnimplementedSwapdoodleServer
// for forward compatibility.
type SwapdoodleServer interface {
	GetPresignedUrlForReportId(context.Context, *GetPresignedUrlForReportIdRequest) (*GetPresignedUrlForReportIdResponse, error)
	mustEmbedUnimplementedSwapdoodleServer()
}

// UnimplementedSwapdoodleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwapdoodleServer struct{}

func (UnimplementedSwapdoodleServer) GetPresignedUrlForReportId(context.Context, *GetPresignedUrlForReportIdRequest) (*GetPresignedUrlForReportIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresignedUrlForReportId not implemented")
}
func (UnimplementedSwapdoodleServer) mustEmbedUnimplementedSwapdoodleServer() {}
func (UnimplementedSwapdoodleServer) testEmbeddedByValue()                    {}

// UnsafeSwapdoodleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwapdoodleServer will
// result in compilation errors.
type UnsafeSwapdoodleServer interface {
	mustEmbedUnimplementedSwapdoodleServer()
}

func RegisterSwapdoodleServer(s grpc.ServiceRegistrar, srv SwapdoodleServer) {
	// If the following call pancis, it indicates UnimplementedSwapdoodleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Swapdoodle_ServiceDesc, srv)
}

func _Swapdoodle_GetPresignedUrlForReportId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedUrlForReportIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapdoodleServer).GetPresignedUrlForReportId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Swapdoodle_GetPresignedUrlForReportId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapdoodleServer).GetPresignedUrlForReportId(ctx, req.(*GetPresignedUrlForReportIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Swapdoodle_ServiceDesc is the grpc.ServiceDesc for Swapdoodle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Swapdoodle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swapdoodle.Swapdoodle",
	HandlerType: (*SwapdoodleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPresignedUrlForReportId",
			Handler:    _Swapdoodle_GetPresignedUrlForReportId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swapdoodle.proto",
}
