// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: swapdoodle.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPresignedUrlForReportIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=noteId,proto3" json:"noteId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUrlForReportIdRequest) Reset() {
	*x = GetPresignedUrlForReportIdRequest{}
	mi := &file_swapdoodle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUrlForReportIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUrlForReportIdRequest) ProtoMessage() {}

func (x *GetPresignedUrlForReportIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swapdoodle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUrlForReportIdRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedUrlForReportIdRequest) Descriptor() ([]byte, []int) {
	return file_swapdoodle_proto_rawDescGZIP(), []int{0}
}

func (x *GetPresignedUrlForReportIdRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type GetPresignedUrlForReportIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUrlForReportIdResponse) Reset() {
	*x = GetPresignedUrlForReportIdResponse{}
	mi := &file_swapdoodle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUrlForReportIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUrlForReportIdResponse) ProtoMessage() {}

func (x *GetPresignedUrlForReportIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swapdoodle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUrlForReportIdResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedUrlForReportIdResponse) Descriptor() ([]byte, []int) {
	return file_swapdoodle_proto_rawDescGZIP(), []int{1}
}

func (x *GetPresignedUrlForReportIdResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_swapdoodle_proto protoreflect.FileDescriptor

const file_swapdoodle_proto_rawDesc = "" +
	"\n" +
	"\x10swapdoodle.proto\x12\n" +
	"swapdoodle\";\n" +
	"!GetPresignedUrlForReportIdRequest\x12\x16\n" +
	"\x06noteId\x18\x01 \x01(\tR\x06noteId\"6\n" +
	"\"GetPresignedUrlForReportIdResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\x8b\x01\n" +
	"\n" +
	"Swapdoodle\x12}\n" +
	"\x1aGetPresignedUrlForReportId\x12-.swapdoodle.GetPresignedUrlForReportIdRequest\x1a..swapdoodle.GetPresignedUrlForReportIdResponse\"\x00B\tZ\a./;grpcb\x06proto3"

var (
	file_swapdoodle_proto_rawDescOnce sync.Once
	file_swapdoodle_proto_rawDescData []byte
)

func file_swapdoodle_proto_rawDescGZIP() []byte {
	file_swapdoodle_proto_rawDescOnce.Do(func() {
		file_swapdoodle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swapdoodle_proto_rawDesc), len(file_swapdoodle_proto_rawDesc)))
	})
	return file_swapdoodle_proto_rawDescData
}

var file_swapdoodle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_swapdoodle_proto_goTypes = []any{
	(*GetPresignedUrlForReportIdRequest)(nil),  // 0: swapdoodle.GetPresignedUrlForReportIdRequest
	(*GetPresignedUrlForReportIdResponse)(nil), // 1: swapdoodle.GetPresignedUrlForReportIdResponse
}
var file_swapdoodle_proto_depIdxs = []int32{
	0, // 0: swapdoodle.Swapdoodle.GetPresignedUrlForReportId:input_type -> swapdoodle.GetPresignedUrlForReportIdRequest
	1, // 1: swapdoodle.Swapdoodle.GetPresignedUrlForReportId:output_type -> swapdoodle.GetPresignedUrlForReportIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swapdoodle_proto_init() }
func file_swapdoodle_proto_init() {
	if File_swapdoodle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swapdoodle_proto_rawDesc), len(file_swapdoodle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swapdoodle_proto_goTypes,
		DependencyIndexes: file_swapdoodle_proto_depIdxs,
		MessageInfos:      file_swapdoodle_proto_msgTypes,
	}.Build()
	File_swapdoodle_proto = out.File
	file_swapdoodle_proto_goTypes = nil
	file_swapdoodle_proto_depIdxs = nil
}
